package com.formation.book.service;
import com.formation.book.dto.*; import com.formation.book.exception.*; import com.formation.book.mapper.BookMapper; import com.formation.book.model.Book; import com.formation.book.repository.BookRepository; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class BookService {
 private final BookRepository repository; public BookService(BookRepository repository){this.repository=repository;}
 @Transactional(readOnly=true) public Page<BookResponse> findAll(String title,String author,Pageable p){Page<Book> page;if(title!=null&&author!=null)page=repository.findByTitleContainingIgnoreCaseAndAuthorContainingIgnoreCase(title,author,p);else if(title!=null)page=repository.findByTitleContainingIgnoreCase(title,p);else if(author!=null)page=repository.findByAuthorContainingIgnoreCase(author,p);else page=repository.findAll(p);return page.map(BookMapper::toResponse);}
 @Transactional(readOnly=true) public BookResponse findById(Long id){return BookMapper.toResponse(book(id));}
 public BookResponse create(BookRequest r){if(repository.findByIsbn(r.isbn()).isPresent())throw new StockConflictException("Un livre avec cet ISBN existe déjà");return BookMapper.toResponse(repository.save(new Book(r.title().trim(),r.author().trim(),r.isbn().trim(),r.totalCopies(),r.totalCopies())));}
 public BookResponse update(Long id,BookRequest r){Book b=book(id);if(repository.findByIsbn(r.isbn()).filter(x->!x.getId().equals(id)).isPresent())throw new StockConflictException("Un livre avec cet ISBN existe déjà");if(r.totalCopies()<b.getAvailableCopies())throw new IllegalArgumentException("totalCopies ne peut pas être inférieur au stock disponible");int delta=r.totalCopies()-b.getTotalCopies();b.setTitle(r.title().trim());b.setAuthor(r.author().trim());b.setIsbn(r.isbn().trim());b.setTotalCopies(r.totalCopies());b.setAvailableCopies(b.getAvailableCopies()+Math.max(delta,0));return BookMapper.toResponse(repository.save(b));}
 public void delete(Long id){Book b=book(id);if(b.getAvailableCopies()<b.getTotalCopies())throw new StockConflictException("Impossible de supprimer un livre avec des exemplaires prêtés");repository.delete(b);}
 public BookResponse decrement(Long id){Book b=book(id);if(b.getAvailableCopies()<=0)throw new StockConflictException("Aucun exemplaire disponible pour ce livre");b.setAvailableCopies(b.getAvailableCopies()-1);return BookMapper.toResponse(repository.saveAndFlush(b));}
 public BookResponse increment(Long id){Book b=book(id);if(b.getAvailableCopies()>=b.getTotalCopies())throw new StockConflictException("Le stock disponible ne peut pas dépasser le nombre total");b.setAvailableCopies(b.getAvailableCopies()+1);return BookMapper.toResponse(repository.saveAndFlush(b));}
 private Book book(Long id){return repository.findById(id).orElseThrow(()->new BookNotFoundException(id));}
}
