package com.formation.loan.service;
import com.formation.loan.client.BookClient; import com.formation.loan.dto.*; import com.formation.loan.exception.*; import com.formation.loan.mapper.LoanMapper; import com.formation.loan.model.*; import com.formation.loan.repository.LoanRepository; import feign.FeignException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*;
@Service @Transactional public class LoanService { private final LoanRepository repo; private final BookClient books; public LoanService(LoanRepository r,BookClient b){repo=r;books=b;}
 @Transactional(readOnly=true) public List<LoanResponse> findAll(){return repo.findByDeletedFalse().stream().map(l->sync(l)).toList();} @Transactional(readOnly=true) public LoanResponse findById(Long id){Loan l=repo.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new LoanNotFoundException(id));return sync(l);}
 public LoanResponse create(LoanRequest r){String member=r.memberName().trim();if(repo.countByMemberNameIgnoreCaseAndStatusAndDeletedFalse(member,LoanStatus.ACTIVE)>=3)throw new LoanException(409,"Un membre ne peut pas avoir plus de trois emprunts actifs");BookDto b=books.findById(r.bookId());if(b.availableCopies()==0)throw new LoanException(409,"Aucun exemplaire disponible pour ce livre");books.decrement(r.bookId());Loan l=new Loan(member,b.id(),b.title(),b.author(),b.isbn(),LocalDate.now());try{return LoanMapper.toResponse(repo.save(l));}catch(RuntimeException e){try{books.increment(r.bookId());}catch(Exception ignored){}throw e;}}
 public LoanResponse returnLoan(Long id){Loan l=repo.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new LoanNotFoundException(id));if(l.getStatus()!=LoanStatus.ACTIVE)throw new LoanException(409,"cet emprunt est déjà terminé");books.increment(l.getBookId());l.setStatus(LoanStatus.RETURNED);l.setReturnDate(LocalDate.now());return LoanMapper.toResponse(repo.save(l));}
 public void delete(Long id){Loan l=repo.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new LoanNotFoundException(id));if(l.getStatus()==LoanStatus.ACTIVE)throw new LoanException(409,"Un emprunt actif ne peut pas être supprimé");l.setDeleted(true);repo.save(l);}
 private LoanResponse sync(Loan l){try{BookDto b=books.findById(l.getBookId());l.setBookTitle(b.title());l.setBookAuthor(b.author());}catch(Exception ignored){}return LoanMapper.toResponse(l);}
}
